<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gracias por registrarte</title>
    <style>
        h1{
            color: cadetblue;
        }
    </style>
</head>
<body>
<h1>Ссылка на регистрацию</h1>
<h2><a href="http://localhost:8080/confirm/${confirm_code}">Pasa por este Link</a> </h2>
</body>
</html>