<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forgot Password Success</title>
    <!-- Agrega tus estilos CSS aquí -->
</head>
<body>
<h1>¡Correo electrónico enviado!</h1>
<p>Se ha enviado un correo electrónico con instrucciones para restablecer tu contraseña. Por favor, revisa tu bandeja de entrada.</p>
<!-- Puedes agregar más contenido si lo deseas -->
</body>
</html>
